export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const SET_LOGIN_ERROR_MESSAGE = 'SET_LOGIN_ERROR_MESSAGE';
export const CLEAR_LOGIN_ERROR_MESSAGE = 'CLEAR_LOGIN_ERROR_MESSAGE';
export const SET_USER = 'SET_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_INITIAL_ROUTE_NAME = 'SET_INITIAL_ROUTE_NAME';
export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const IS_LOADING = 'IS_LOADING';


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';


export const LOWONGAN_REQUEST = 'LOWONGAN_REQUEST';
export const LOWONGAN_SUCCESS = 'LOWONGAN_SUCCESS';
export const LOWONGAN_FAILED = 'LOWONGAN_FAILED';

export const DETAILS_LOWONGAN_REQUEST = 'DETAILS_LOWONGAN_REQUEST';
export const DETAILS_LOWONGAN_SUCCESS = 'DETAILS_LOWONGAN_SUCCESS';
export const DETAILS_LOWONGAN_FAILED = 'DETAILS_LOWONGAN_FAILED';

export const MY_APPLY_REQUEST = 'MY_APPLY_REQUEST';
export const MY_APPLY_SUCCESS = 'MY_APPLY_SUCCESS';
export const MY_APPLY_FAILED = 'MY_APPLY_FAILED';

export const APPLY_REQUEST = 'APPLY_REQUEST';
export const APPLY_SUCCESS = 'APPLY_SUCCESS';
export const APPLY_FAILED = 'APPLY_FAILED';

export const DETAIL_MY_APPLY_REQUEST = 'DETAIL_MY_APPLY_REQUEST';
export const DETAIL_MY_APPLY_SUCCESS = 'DETAIL_MY_APPLY_SUCCESS';
export const DETAIL_MY_APPLY_FAILED = 'DETAIL_MY_APPLY_FAILED';
